### ISSUE TITLE
Compatibility with Flutter 1.5 and Dart 2.2.0

### ISSUE THREAD

**Issue by AbdoXLabs** [xsahil03x/giffy_dialog#9]
`file:///Users/USER/.pub-cache/hosted/pub.dartlang.org/flare_flutter-1.5.0/lib/flare.dart:1028:18: Error: The argument type 'Int32List' can't be assigned to the parameter type 'Uint16List'.
 - 'Int32List' is from 'dart:typed_data'.
 - 'Uint16List' is from 'dart:typed_data'.
Try changing the type of the parameter, or casting the argument to 'Uint16List'.
        indices: _indices, textureCoordinates: _uvBuffer);`

**Comment by Purus** [comment]
I can confirm on this issue too.

**Comment by Purus** [comment]
The flare plugin needs to be fixed and the latest version has to be included in this package when its released.

untill then, you can override the flare package version in your app's pubspec.yml file.

```
dependency_overrides:
  flare_flutter:
    git:
      url: https://github.com/2d-inc/Flare-Flutter.git
      path: flare_flutter
      ref: dev
```
